# Generated by Django 5.1.15 on 2026-05-10 02:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('km_inicial', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='KM inicial')),
                ('km_final', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='KM final')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor bruto (R$)')),
                ('total_km', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total km')),
                ('total_horas', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='Total horas')),
                ('preco_por_km', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='R$/km')),
                ('preco_por_hora', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='R$/hora')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
    ]
